version: "3.8"
services:
  dnsfw:
    build: .
    container_name: dnsfw
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8080:8080"
    volumes:
      - ./config:/config:ro
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped


